[project]
name = "ai-playground"
version = "0.1.0"
requires-python = ">=3.13,<4.0"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
python-dotenv = "^1.1.0"
google-genai = "^1.8.0"
pillow = "^11.1.0"
openai = "^1.70.0"
vertexai = "^1.71.1"
